package test.app.project.vo;


/**
 * 편의시설목록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class AmenitiesVo {


	/** 편의시설식별키. */
	private int amenities_num;

	/** 편의시설명. */
	private String amenities_name;

	/** 편의시설소개. */
	private String amenities_content;

	/** 원본파일명. */
	private String orgfilename;

	/** 저장파일명. */
	private String savefilename;

	public AmenitiesVo() {
	
	}

	public AmenitiesVo(int amenities_num, String amenities_name, String amenities_content, String orgfilename,
			String savefilename) {
		super();
		this.amenities_num = amenities_num;
		this.amenities_name = amenities_name;
		this.amenities_content = amenities_content;
		this.orgfilename = orgfilename;
		this.savefilename = savefilename;
	}

	public int getAmenities_num() {
		return amenities_num;
	}

	public void setAmenities_num(int amenities_num) {
		this.amenities_num = amenities_num;
	}

	public String getAmenities_name() {
		return amenities_name;
	}

	public void setAmenities_name(String amenities_name) {
		this.amenities_name = amenities_name;
	}

	public String getAmenities_content() {
		return amenities_content;
	}

	public void setAmenities_content(String amenities_content) {
		this.amenities_content = amenities_content;
	}

	public String getOrgfilename() {
		return orgfilename;
	}

	public void setOrgfilename(String orgfilename) {
		this.orgfilename = orgfilename;
	}

	public String getSavefilename() {
		return savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}

}
