package test.app.project.vo;


/**
 * 종목(종류) 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BEventVo {

	/** 종목식별키. */
	private int bnum;

	/** 업태. */
	private int snum;

	/** 종목명. */
	private String btype;


	/**
	 * 생성자.
	 */
	public BEventVo() {
	}


	public BEventVo(int bnum, int snum, String btype) {
		super();
		this.bnum = bnum;
		this.snum = snum;
		this.btype = btype;
	}


	public int getBnum() {
		return bnum;
	}


	public void setBnum(int bnum) {
		this.bnum = bnum;
	}


	public int getSnum() {
		return snum;
	}


	public void setSnum(int snum) {
		this.snum = snum;
	}


	public String getBtype() {
		return btype;
	}


	public void setBtype(String btype) {
		this.btype = btype;
	}

}
