package test.app.project.vo;

import java.sql.Date;

/**
 * 예약테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BookingTableVo {


	/** 예약번호. */
	private int booking_num;

	/** 객실정보. */
	private int room_num;

	/** 회원테이블. */
	private String mid;

	/** 결제금액. */
	private int pay_Money;

	/** 예약신청날짜. */
	private java.sql.Date booksDate;

	/** 숙박시작일. */
	private java.sql.Date startDate;

	/** 숙박종료일. */
	private java.sql.Date endDate;

	/** 예약상태. */
	private String bookStatus;


	/**
	 * 생성자.
	 */
	public BookingTableVo() {
	}


	public BookingTableVo(int booking_num, int room_num, String mid, int pay_Money, Date booksDate, Date startDate,
			Date endDate, String bookStatus) {
		super();
		this.booking_num = booking_num;
		this.room_num = room_num;
		this.mid = mid;
		this.pay_Money = pay_Money;
		this.booksDate = booksDate;
		this.startDate = startDate;
		this.endDate = endDate;
		this.bookStatus = bookStatus;
	}


	public int getBooking_num() {
		return booking_num;
	}


	public void setBooking_num(int booking_num) {
		this.booking_num = booking_num;
	}


	public int getRoom_num() {
		return room_num;
	}


	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}


	public String getMid() {
		return mid;
	}


	public void setMid(String mid) {
		this.mid = mid;
	}


	public int getPay_Money() {
		return pay_Money;
	}


	public void setPay_Money(int pay_Money) {
		this.pay_Money = pay_Money;
	}


	public java.sql.Date getBooksDate() {
		return booksDate;
	}


	public void setBooksDate(java.sql.Date booksDate) {
		this.booksDate = booksDate;
	}


	public java.sql.Date getStartDate() {
		return startDate;
	}


	public void setStartDate(java.sql.Date startDate) {
		this.startDate = startDate;
	}


	public java.sql.Date getEndDate() {
		return endDate;
	}


	public void setEndDate(java.sql.Date endDate) {
		this.endDate = endDate;
	}


	public String getBookStatus() {
		return bookStatus;
	}


	public void setBookStatus(String bookStatus) {
		this.bookStatus = bookStatus;
	}

}
