package test.app.project.vo;

import java.sql.Date;

/**
 * 이벤트 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EventVo {


	/** 이벤트식별키. */
	private int eventNum;

	/** 이벤트제목. */
	private String etitle;

	/** 이벤트등록일. */
	private Date eregdate;

	/** 이벤트조회수. */
	private int ehit;

	/** 이벤트 시작일. */
	private Date estartdate;

	/** 이벤트종료일. */
	private Date eenddate;

	/**
	 * 생성자.
	 */
	public EventVo() {
	}

	public EventVo(int eventNum, String etitle, Date eregdate, int ehit, Date estartdate, Date eenddate) {
		super();
		this.eventNum = eventNum;
		this.etitle = etitle;
		this.eregdate = eregdate;
		this.ehit = ehit;
		this.estartdate = estartdate;
		this.eenddate = eenddate;
	}

	public int getEventNum() {
		return eventNum;
	}

	public void setEventNum(int eventNum) {
		this.eventNum = eventNum;
	}

	public String getEtitle() {
		return etitle;
	}

	public void setEtitle(String etitle) {
		this.etitle = etitle;
	}

	public Date getEregdate() {
		return eregdate;
	}

	public void setEregdate(Date eregdate) {
		this.eregdate = eregdate;
	}

	public int getEhit() {
		return ehit;
	}

	public void setEhit(int ehit) {
		this.ehit = ehit;
	}

	public Date getEstartdate() {
		return estartdate;
	}

	public void setEstartdate(Date estartdate) {
		this.estartdate = estartdate;
	}

	public Date getEenddate() {
		return eenddate;
	}

	public void setEenddate(Date eenddate) {
		this.eenddate = eenddate;
	}



}
