package test.app.project.vo;

/**
 * 이벤트 이미지 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class EventimagesVo {

	/** 이미지식별키. */
	private int eimgnum;

	/** 원본파일명. */
	private String orgfilename;

	/** 저장파일명. */
	private String savefilename;

	private int event_num;

	/**
	 * 생성자.
	 */
	public EventimagesVo() {
	}

	public EventimagesVo(int eimgnum, String orgfilename, String savefilename, int event_num) {
		super();
		this.eimgnum = eimgnum;
		this.orgfilename = orgfilename;
		this.savefilename = savefilename;
		this.event_num = event_num;
	}

	public int getEimgnum() {
		return eimgnum;
	}

	public void setEimgnum(int eimgnum) {
		this.eimgnum = eimgnum;
	}

	public String getOrgfilename() {
		return orgfilename;
	}

	public void setOrgfilename(String orgfilename) {
		this.orgfilename = orgfilename;
	}

	public String getSavefilename() {
		return savefilename;
	}

	public void setSavefilename(String savefilename) {
		this.savefilename = savefilename;
	}

	public int getEvent_num() {
		return event_num;
	}

	public void setEvent_num(int event_num) {
		this.event_num = event_num;
	}

}
