package test.app.project.vo;

/**
 * 질문카테고리 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class FaqcategoryVo {


	/** 카테고리식별키. */
	private int fcnum;

	/** 카테고리명. */
	private String fctype;

	/**
	 * 생성자.
	 */
	public FaqcategoryVo() {
	}

	public FaqcategoryVo(int fcnum, String fctype) {
		super();
		this.fcnum = fcnum;
		this.fctype = fctype;
	}

	public int getFcnum() {
		return fcnum;
	}

	public void setFcnum(int fcnum) {
		this.fcnum = fcnum;
	}

	public String getFctype() {
		return fctype;
	}

	public void setFctype(String fctype) {
		this.fctype = fctype;
	}


}
