package test.app.project.vo;

/**
 * 회원등급테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class GradeVo {


	/** 등급식별키. */
	private int gnum;

	/** 등급명. */
	private String gname;


	/**
	 * 생성자.
	 */
	public GradeVo() {
	}


	public GradeVo(int gnum, String gname) {
		super();
		this.gnum = gnum;
		this.gname = gname;
	}


	public int getGnum() {
		return gnum;
	}


	public void setGnum(int gnum) {
		this.gnum = gnum;
	}


	public String getGname() {
		return gname;
	}


	public void setGname(String gname) {
		this.gname = gname;
	}

}
