package test.app.project.vo;

import java.sql.Date;

/**
 * 공지사항 테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class NoticeVo {


	/** 공지사항번호. */
	private int nnum;

	/** 공지글제목. */
	private String ntitle;

	/** 공지내용. */
	private String ncontent;

	/** 공지날짜. */
	private Date nregdate;

	/**
	 * 생성자.
	 */
	public NoticeVo() {
	}

	public NoticeVo(int nnum, String ntitle, String ncontent, Date nregdate) {
		super();
		this.nnum = nnum;
		this.ntitle = ntitle;
		this.ncontent = ncontent;
		this.nregdate = nregdate;
	}

	public int getNnum() {
		return nnum;
	}

	public void setNnum(int nnum) {
		this.nnum = nnum;
	}

	public String getNtitle() {
		return ntitle;
	}

	public void setNtitle(String ntitle) {
		this.ntitle = ntitle;
	}

	public String getNcontent() {
		return ncontent;
	}

	public void setNcontent(String ncontent) {
		this.ncontent = ncontent;
	}

	public Date getNregdate() {
		return nregdate;
	}

	public void setNregdate(Date nregdate) {
		this.nregdate = nregdate;
	}


}
