package test.app.project.vo;

import java.sql.Date;

/**
 * 결제테이블 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class PaymentVo  {


	/** 결제번호. */
	private int pay_num;

	/** 예약테이블. */
	private int booking_num;

	/** 쿠폰. */
	private int coupon_num;

	/** 최종결제금액. */
	private int pay;

	/** 결제날짜. */
	private Date pa_day;

	/** 결제수단. */
	private String payment_type;

	/**
	 * 생성자.
	 */
	public PaymentVo() {
	}

	public PaymentVo(int pay_num, int booking_num, int coupon_num, int pay, Date pa_day, String payment_type) {
		super();
		this.pay_num = pay_num;
		this.booking_num = booking_num;
		this.coupon_num = coupon_num;
		this.pay = pay;
		this.pa_day = pa_day;
		this.payment_type = payment_type;
	}

	public int getPay_num() {
		return pay_num;
	}

	public void setPay_num(int pay_num) {
		this.pay_num = pay_num;
	}

	public int getBooking_num() {
		return booking_num;
	}

	public void setBooking_num(int booking_num) {
		this.booking_num = booking_num;
	}

	public int getCoupon_num() {
		return coupon_num;
	}

	public void setCoupon_num(int coupon_num) {
		this.coupon_num = coupon_num;
	}

	public int getPay() {
		return pay;
	}

	public void setPay(int pay) {
		this.pay = pay;
	}

	public Date getPa_day() {
		return pa_day;
	}

	public void setPa_day(Date pa_day) {
		this.pa_day = pa_day;
	}

	public String getPayment_type() {
		return payment_type;
	}

	public void setPayment_type(String payment_type) {
		this.payment_type = payment_type;
	}

}
