package test.app.project.vo;

/**
 * Q&A카테고리 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class QnaCategoryVo{


	/** qna카테고리식별키. */
	private int qna_category_num;

	/** qna카테고리명. */
	private String qna_category_name;


	/**
	 * 생성자.
	 */
	public QnaCategoryVo() {
	}


	public QnaCategoryVo(int qna_category_num, String qna_category_name) {
		super();
		this.qna_category_num = qna_category_num;
		this.qna_category_name = qna_category_name;
	}


	public int getQna_category_num() {
		return qna_category_num;
	}


	public void setQna_category_num(int qna_category_num) {
		this.qna_category_num = qna_category_num;
	}


	public String getQna_category_name() {
		return qna_category_name;
	}


	public void setQna_category_name(String qna_category_name) {
		this.qna_category_name = qna_category_name;
	}

}
