package test.app.project.vo;


/**
 * 리뷰이미지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class ReiewImgVo {


	/** 리뷰이미지식별번호. */
	private int review_img_num;

	/** 후기게시판. */
	private int review_num;

	/** 리뷰이미지원본명. */
	private String review_org_name;

	/** 리뷰이미지저장명. */
	private String review_save_name;

	/**
	 * 생성자.
	 */
	public ReiewImgVo() {
	}

	public ReiewImgVo(int review_img_num, int review_num, String review_org_name, String review_save_name) {
		super();
		this.review_img_num = review_img_num;
		this.review_num = review_num;
		this.review_org_name = review_org_name;
		this.review_save_name = review_save_name;
	}

	public int getReview_img_num() {
		return review_img_num;
	}

	public void setReview_img_num(int review_img_num) {
		this.review_img_num = review_img_num;
	}

	public int getReview_num() {
		return review_num;
	}

	public void setReview_num(int review_num) {
		this.review_num = review_num;
	}

	public String getReview_org_name() {
		return review_org_name;
	}

	public void setReview_org_name(String review_org_name) {
		this.review_org_name = review_org_name;
	}

	public String getReview_save_name() {
		return review_save_name;
	}

	public void setReview_save_name(String review_save_name) {
		this.review_save_name = review_save_name;
	}

}
