package test.app.project.vo;


/**
 * 객실정보 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomsVo{


	/** 방식별번호. */
	private int room_num;

	/** 업소테이블. */
	private int house_num;

	/** 객실명. */
	private String roomname;

	/** 객실가격. */
	private int room_price;

	/** 객실정보. */
	private String room_info;

	/** 룸체크인. */
	private int room_check;

	/** 최대인원. */
	private int max_Personnel;


	/**
	 * 생성자.
	 */
	public RoomsVo() {
	}


	public RoomsVo(int room_num, int house_num, String roomname, int room_price, String room_info, int room_check,
			int max_Personnel) {
		super();
		this.room_num = room_num;
		this.house_num = house_num;
		this.roomname = roomname;
		this.room_price = room_price;
		this.room_info = room_info;
		this.room_check = room_check;
		this.max_Personnel = max_Personnel;
	}


	public int getRoom_num() {
		return room_num;
	}


	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}


	public int getHouse_num() {
		return house_num;
	}


	public void setHouse_num(int house_num) {
		this.house_num = house_num;
	}


	public String getRoomname() {
		return roomname;
	}


	public void setRoomname(String roomname) {
		this.roomname = roomname;
	}


	public int getRoom_price() {
		return room_price;
	}


	public void setRoom_price(int room_price) {
		this.room_price = room_price;
	}


	public String getRoom_info() {
		return room_info;
	}


	public void setRoom_info(String room_info) {
		this.room_info = room_info;
	}


	public int getRoom_check() {
		return room_check;
	}


	public void setRoom_check(int room_check) {
		this.room_check = room_check;
	}


	public int getMax_Personnel() {
		return max_Personnel;
	}


	public void setMax_Personnel(int max_Personnel) {
		this.max_Personnel = max_Personnel;
	}


}
