package test.app.project.vo;


/**
 * 객실이미지 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class RoomsImgVo  {


	/** 객실이미지식별키. */
	private int rooms_img_num;

	/** 객실정보. */
	private int room_num;

	/** 객실이미지원본명. */
	private String room_org_name;

	/** 객실이미지저장명. */
	private String room_save_name;

	/**
	 * 생성자.
	 */
	public RoomsImgVo() {
	}

	public RoomsImgVo(int rooms_img_num, int room_num, String room_org_name, String room_save_name) {
		super();
		this.rooms_img_num = rooms_img_num;
		this.room_num = room_num;
		this.room_org_name = room_org_name;
		this.room_save_name = room_save_name;
	}

	public int getRooms_img_num() {
		return rooms_img_num;
	}

	public void setRooms_img_num(int rooms_img_num) {
		this.rooms_img_num = rooms_img_num;
	}

	public int getRoom_num() {
		return room_num;
	}

	public void setRoom_num(int room_num) {
		this.room_num = room_num;
	}

	public String getRoom_org_name() {
		return room_org_name;
	}

	public void setRoom_org_name(String room_org_name) {
		this.room_org_name = room_org_name;
	}

	public String getRoom_save_name() {
		return room_save_name;
	}

	public void setRoom_save_name(String room_save_name) {
		this.room_save_name = room_save_name;
	}

}
