package test.app.project.vo;


/**
 * 업태 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class StayVo  {

	/** 업태식별키. */
	private int snum;

	/** 업태명. */
	private String sname;

	/**
	 * 생성자.
	 */
	public StayVo() {
	}

	public StayVo(int snum, String sname) {
		super();
		this.snum = snum;
		this.sname = sname;
	}

	public int getSnum() {
		return snum;
	}

	public void setSnum(int snum) {
		this.snum = snum;
	}

	public String getSname() {
		return sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

}
