package test.app.project.vo;

/**
 * 찜목록 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class WishlistVo  {


	/** 찜목록식별키. */
	private int wish_num;

	/** 회원테이블. */
	private String mid;

	/** 업소테이블. */
	private int house_num;

	/**
	 * 생성자.
	 */
	public WishlistVo() {
	}

	public WishlistVo(int wish_num, String mid, int house_num) {
		super();
		this.wish_num = wish_num;
		this.mid = mid;
		this.house_num = house_num;
	}

	public int getWish_num() {
		return wish_num;
	}

	public void setWish_num(int wish_num) {
		this.wish_num = wish_num;
	}

	public String getMid() {
		return mid;
	}

	public void setMid(String mid) {
		this.mid = mid;
	}

	public int getHouse_num() {
		return house_num;
	}

	public void setHouse_num(int house_num) {
		this.house_num = house_num;
	}

}
